### ISSUE TITLE
[BUG] All api properties are optional

### ISSUE THREAD

**Issue by bakasmarius** [Savory/Danet-Swagger#6]
*BUG*

**Current behavior**
It doesn't matter how I decorate a property, all of these will be generated as optional:
```
  @Optional()
  @ApiProperty()
  name1?: string

  @ApiProperty()
  name2: string

  @Optional()
  name3?: string
```
In generated JSON, each of the items in `components` -> `schemas` -> only has `properties` property, but does not have `type` and `required` properties.

**Expected behavior**
`name1` should be optional, `name2` should be required, `name3` should be optional.
```
  @Optional()
  @ApiProperty()
  name1?: string

  @ApiProperty()
  name2: string

  @Optional()
  name3?: string
```
In generated JSON, each of the items in `components` -> `schemas` -> should have  `type`, `properties`, and `required` properties.

**Comment by Sorikairox** [comment]
Solved in 1.4.0
