### ISSUE TITLE
Do you support OpenAPI's description?

### ISSUE THREAD

**Issue by DrayChou** [Savory/Danet-Swagger#9]
Hello,

I am using your project and would like to add comments to my API and provide descriptions for the parameters. I have looked through the documentation but couldn't find a way to add descriptions. Could you please let me know how I can add these descriptions?

If this feature is not currently supported, is there a plan to implement it in future versions? If so, could you provide a rough timeline for when this might be developed?

Thank you for your help!

----------

Bonjour,

J'utilise votre projet et j'aimerais ajouter des commentaires à mon API ainsi que des descriptions pour les paramètres. J'ai consulté la documentation, mais je n'ai pas trouvé de moyen d'ajouter des descriptions. Pourriez-vous me dire comment je peux ajouter ces descriptions ?

Si cette fonctionnalité n'est pas actuellement prise en charge, y a-t-il un plan pour l'implémenter dans les futures versions ? Si oui, pourriez-vous fournir un calendrier approximatif pour le développement de cette fonctionnalité ?

Merci pour votre aide !

**Comment by Sorikairox** [comment]
@DrayChou My apologies for the delay. I will implement it either this week or next week !

**Comment by Sorikairox** [comment]
@DrayChou version 2.3.1 is out with this feature !
